name: Sync MLX Files

on:
  push:
    branches: [ main ]
    paths:
    - '**.mlx'

jobs:
  copy-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: 'AaronBrennan1/tutorials_dummy'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Destination Repo
        uses: actions/checkout@v2
        with:
          repository: 'AaronBrennan1/cobra_ghpages_dummy'
          token: ${{ secrets.DEST_REPO_TOKEN }}
          path: destination-repo

      - name: Find changed mlx files
        id: getfile
        run: |
          git diff --name-only HEAD^..HEAD
          FILES=$(git diff --name-only HEAD^..HEAD | grep '\.mlx')
          echo $FILES
          echo "::set-output name=file::$FILES"



      - name: Copy Files
        run: |
          mkdir -p "destination-repo/stable/tutorials/$(dirname "${{ steps.getfile.outputs.file }}")"
          cp "${{ steps.getfile.outputs.file }}" "destination-repo/stable/tutorials/${{ steps.getfile.outputs.file }}"
        working-directory: ${{ github.workspace }}

      - name: Push to Destination Repo
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Sync mlx files from source repo" || echo "No changes to commit"
          git push origin main
        working-directory: ${{ github.workspace }}/destination-repo

