name: Sync MLX Files

on:
  push:
    branches: [ main ]
    paths:
    - '**.mlx'

jobs:
  copy-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: 'AaronBrennan1/tutorials_dummy'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Find changed mlx files
        id: getfile
        run: |
          echo "::set-output name=file::$(git diff --name-only HEAD~1 HEAD | grep '\.mlx')"

      - name: Sync with Destination Repo
        run: ./build.sh AaronBrennan1/cobra_ghpages_dummy ${{ secrets.DEST_REPO_TOKEN }} ${{ steps.getfile.outputs.file }}
        if: steps.getfile.outputs.file != ''
