name: Sync MLX Files

on:
  push:
    branches: [ main ]
    paths:
    - '**.mlx'

jobs:
  copy-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2
        with:
          repository: 'AaronBrennan1/tutorials_dummy'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get All Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Find changed files
        id: getfile
        run: |
          files=$(echo "${{ steps.files.outputs.all }}" | grep -E '\.(mlx|m|html|pdf)$')
          echo "::set-output name=file::$files"
      
      
      - name: Give execute permission to the script
        run: chmod +x build.sh


      - name: Sync with Destination Repo
        run: ./build.sh AaronBrennan1/cobra_ghpages_dummy ${{ secrets.DEST_REPO_TOKEN }} ${{ steps.getfile.outputs.file }} ${{ secrets.EMAIL }}
        if: steps.getfile.outputs.file != ''
